Remove unnecessary goroutine of loki writer
netobserv/flowlogs-pipeline pull request #327
Opened 2022-10-17 13:25 UTC by OlivierCazade

Loki write use a goroutine to do async send to loki.

This is unnecessary because loki client is already doing async send.

I tested this change under some load and did not see any impact.

2022-10-18 09:13 UTC, mariomac approved these changes

2022-10-18 14:56 UTC, ronensc approved these changes

2022-10-19 06:28 UTC, jotak requested changes
L256 there's this comment that I wrote: `// TODO / FIXME / FIGUREOUT bla bla` => it should be removed, as well as the channel creation and the associated gauge

2022-10-21 15:42 UTC, jotak approved these changes
thanks @OlivierCazade 
lgtm

2022-10-24 06:56 UTC, merged